# vim: syntax=python

Import('env', 'arch')

sources = Split('''
	init/init.c
''')

o = SConscript('arch/%s/SConscript' % arch)
sources.append(o)

env.Append(CPPPATH=['#src/kernel/hal/include/'])
Export('env')

libs = [''] #empty list of libs
paths = ['.']
#['lib','mm','hal','arch','boot','drivers','init']:
for subdir in ['lib','mm','drivers','boot','init','hal']:
    lib = SConscript('%s/SConscript' % subdir)
    print lib
    libs.append(lib)
    paths.append(subdir)
   # env.Append(LIBS=lib)

paths.append('#src/userland/')
libs.append('userland')

env.Append(LINKFLAGS=['-T', 'src/kernel/link.ld', '-Map', 'src/kernel/kernel.sym'])
env.Append(CCFLAGS=['-I', 'include/arch/%s' % arch])


env.Program('kernel', [sources,Glob('*.c'),Glob('*.s')], LIBS=libs, LIBPATH=paths)
