# vim: syntax=python

Import('env', 'arch')

sources = Split('''
	init/init.c
''')

o = SConscript('arch/%s/SConscript' % arch)
sources.append(o)

env.Append(CPPPATH=['#src/kernel/hal/include/'])
Export('env')

libs = [''] #empty list of libs
paths = ['.'] #include in path 

for subdir in ['boot','misc','drivers','mm','lib','#src/userland','hal']:
    lib = SConscript('%s/SConscript' % subdir)
    print lib
    env.Append(LIBS=[lib])
    env.Append(LIBPATH=[subdir])
    

env.Append(LINKFLAGS=['-T', 'src/kernel/link.ld', '-Map', 'src/kernel/kernel.sym'])
env.Append(CCFLAGS=['-I', 'include/arch/%s' % arch])

env.Program('kernel', sources)
