# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq')

sources = []

kernel = env.Clone()

if arch == 'x86':
	sources += [
	]

sources += [
]

distreq += ['src/lib/krnllib/krnllib.lib']

kernel.StaticLibrary('krnllib', sources)
