before_script:
#  - sudo apt-get -y update
#  - sudo apt-get -y install qemu clang nasm mkisofs
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


#script: make && ./test.sh
script: false

notifications:
#  webhooks:
#    - http://rcmp.programble.co.cc/irc.tenthbit.net/programming
#    - http://rcmp.programble.co.cc/irc.freenode.net/duxos
  
  email:
    on_success: change # default: change
    on_failure: change # default: always

