before_script:
#  - sudo apt-get -y update
  - sudo apt-get --fix-missing -y install qemu clang nasm mkisofs
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


script: cp config.mk.dist config.mk && time make # && ./test.sh

notifications:
  webhooks:
    - http://rcmp.programble.co.cc/irc.freenode.net/duckyy
    - http://rcmp.programble.co.cc/irc.freenode.net/duxos
  
  email:
    on_success: change # default: change
    on_failure: change # default: always

