# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq')

sources = []

kernel = env.Clone()

if arch == 'i386':
	sources += [
		'./arch/i386/display.c',
		'./arch/i386/interrupts.c',
		'./arch/i386/port.c',
		'./arch/i386/shutdown.c',
	]
	kernel.Append(LINKFLAGS=['-T', 'src/krnl/arch/i386/link.ld'])

sources += [
	'./boot/loader.asm',
	'./init/init.c',
	'./core/ipl.c',
	'./core/shutdown.c',
	'./core/text.c',
]

distreq += ['src/krnl/krnl.exe']

kernel.Program('krnl', sources)
