# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq')

hal = env.Clone()

sources = [
	'exceptions.asm',
	'gdt.asm',
	'hal.c',
	'idt.c',
	'isrs.c',
	'irqs.c',
	'ports.c',
	'display.c',
	'interrupts.c',
	'shutdown.c',
]

distreq += ['src/metodo/hal/i386/hal.lib']

hal.StaticLibrary('hal', sources)

