# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq')

hal = env.Clone()

sources = [
	'hal.c',
	'gdt.asm',
	'ports.c',
]

distreq += ['src/metodo/hal/i386/hal.lib']

hal.StaticLibrary('hal', sources)

