# vim: syntax=python
Import('env', 'arch', 'buildtype', 'distreq')
Import('sources', 'metodo')

sources += [
	'misc/stack_dump.asm',
	'misc/panic.c',
	'misc/misc.c',
	'misc/stop.c',
	'misc/debug.c'
]
