#define __DUX_BUILT_ARCH__ "x86_64"
#define __DUX_BUILT_OS__ "GNU/Linux"
#define __DUX_BUILT_VERSION__ "2.6.30-ARCH"
#define __DUX_BUILT_NAME__ "desk"
#define __DUX_BUILT_DATE__ "Sun Jul 19 20:48:28 EDT 2009"
