# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq', 'sources')

modules = env.Clone()

modules.Append(LINKFLAGS=['-Ttext', '0x300000'])

modules.Append(LIBS=[File('#src/metodo/hal/%s/hal.lib' % arch)])
modules.Append(LIBS=[File('#src/vfs/vfs.lib')])

# Driver modules (not required by the kernel)

module_sources = [
]

for file in module_sources:
	modules.Program(file.replace('.c', ''), [file])
	distreq += ['src/metodo/driver/generic/'+file.replace('.c', '.o')]

# Drivers that are required by the kernel

sources += [
	'driver/generic/display.c',
]

Export('sources', 'distreq')
