# vim: syntax=python

#Sconscript for userland
Import('env', 'arch')

sources = Split('''
         colorchart.c
         console.c
         pong.c
''')
lib = ['userland']
env.Library(lib,sources)
Return('lib')
