# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq')

sources = []

initrd = env.Clone()

sources += [
	'./initrd.c',
]

distreq += ['src/initrd/initrd.lib']

initrd.StaticLibrary('initrd', sources)
