#+LINK: grub http://www.gnu.org/software/grub/manual/html_node/

First file to look at:

<duckinator> nixeagle: src/kernel/init/init.c


* Build
make cross compiler
 : cd tools/cross;make;cd -

run kernel
 : cd ../../;scons;./run.sh

Don't forget to read http://wiki.github.com/RockerMONO/dux/compiling

 : export  ~/duxcc:~/duxcc/bin:~/duxincludes

Export these to your path, using zsh the command is:
 : path=( ~/duxcc ~/duxcc/bin ~/duxincludes $path)
Be sure to put this in your ~/.zshenv


* Emacs
Make sure your indention is set to use tabs for C mode instead of
spaces.

 : (add-hook 'c-mode-hook (lambda () (setq indent-tabs-mode t)))


* Debug
*** Howto use GDB and bochs
    Thanks to scott for the following bochs instructions. Not 100%
    positive this works with dux yet.

    1. compile bochs with --enable-gdb-stub
    2. In bochsrc add:
    : gdbstub: enabled=1, port=1234, text_base=0, data_base=0, bss_base=0
    3. in gdb
    : target remote :1234

* start.asm
First thing that needs done is setting up grub. [fn:1] Dux loads
directly, no _grub_ chain loading. [fn:2] Because dux is multiboot
complient [fn:3]the very first bit of asm after declaring a few external
functions is the multiboot header.

*** Multiboot complience
    Multiboot complience means including an additional header within the
    _first_ 8192 bytes of the OS image that is longword aligned. The
    header layout is specified at [[http://www.gnu.org/software/grub/manual/multiboot/multiboot.html#Header-layout][header layout]]. Three of the fields are
    required [[magic field][magic]], flags, and checksum. [fn:5] Flags is 32 bits used to
    indicate requirements to the bootloader.[fn:4] Read up on the rest.

*** ASM Refresher
    20 basic instruction classes explained in [[http://maven.smith.edu/~thiebaut/ArtOfAssembly/CH03/CH03-3.html#HEADING3-37][Art of Assembly language]]

* Terms
  - <<<longword>>> :: 32 bit aligned
  - <<<magic field>>> :: 0x1BADB002 used to identify the multiboot
       header. This is offset 0.



* notes
Memory upper bound:
  :  mbd->mem_upper*1024
* Footnotes

[fn:1] Grub docs at http://www.fifi.org/doc/grub-doc/html/grub.html#SEC_Top

[fn:2] Multi-boot according to duckinator is described in 
[[http://www.gnu.org/software/grub/manual/html_node/Loading-an-operating-system-directly.html][Loading-an-operating-system-directly]].

[fn:3] [[http://www.gnu.org/software/grub/manual/multiboot/multiboot.html][Multiboot specifiction]]

[fn:4] Dux asks for =MODULEALIGN | MEMINFO=

[fn:5] checksum's against the other two required flags 
=-(MAGIC + FLAGS)=

*ni
