# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq')

hal = env.Clone()

sources = [
	'task.c',
	#'tss.c',
	#'exceptions.asm',
	'gdt.asm',
	'hal.c',
	#'syscall.c',
	'idt.c',
	'isrs.c',
	'irqs.c',
	'ports.c',
	'interrupts.c',
	'shutdown.c',
	'mm/memory.c',
	'scheduler.c'
]

distreq += ['src/metodo/hal/x86_64/hal.lib']

hal.StaticLibrary('hal', sources)

