# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq', 'sources')

modules = env.Clone()

modules.Append(LINKFLAGS=['-Ttext', '0x300000'])

modules.Append(LIBS=[File('#src/metodo/hal/%s/hal.lib' % arch)])
modules.Append(LIBS=[File('#src/vfs/vfs.lib')])

# Driver modules (not required by the kernel)

module_sources = [
	'serial.c',
]

for file in module_sources:
	modules.Program(file.replace('.c', ''), [file])
	object_file = 'src/metodo/modules/driver/%s/%s' % (arch, file.replace('.c', '.exe'))
	distreq += [object_file]

Export('sources', 'distreq')
