# vim: syntax=python

Import('env', 'arch', 'buildtype')

sources = [
]

user = env.Clone()
user.Append(LINKFLAGS=['-Map', 'user/user.map', '-Ttext', '0x200000'])

if arch == 'x86':
	sources += [
	]

sources += [
	'user.c',
#	'colorchart.c',
#	'console.c',
#	'pong.c',
]

user.Program('user', sources)
