# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq')

sources = []

metodo = env.Clone()

SConscript('hal/%s/SConscript' % arch)
metodo.Append(LIBS=[File('#src/metodo/hal/%s/hal.lib' % arch)])
metodo.Append(LIBS=[File('#src/vfs/vfs.lib')])
metodo.Append(LIBS=[File('#src/initrd/initrd.lib')])

Export('sources', 'metodo')
SConscript('boot/%s/SConscript' % arch)
SConscript('core/SConscript')
SConscript('misc/SConscript')
SConscript('colpa/SConscript')

sources += [
	'init/init.c',
	'init/elfloader.c',
	'init/tests.c',
	'lib/zeromemory.c',
	'lib/string.c',
	'bochs/debug.c'
]

distreq += ['src/metodo/metodo.exe']

metodo.Program('metodo', sources)
